### PR TITLE
feat: Add AppLogWriter LWC for easy log creation

### PR DESCRIPTION
**Pull request by RyanSchierholz**
This PR adds a new Lightning Web Component that provides an intuitive interface for creating log entries.

Features:
- Button-style radio group for log level selection (DEBUG, INFO, WARN)
- Real-time validation of message input
- Success notifications
- Maintains selected log level between entries
- Default INFO level selection

The component enhances the logging system by providing:
- Easy testing and demonstration functionality
- Quick log creation from any Lightning page
- Visual feedback on log creation success

Technical notes:
- Uses @AuraEnabled methods from LogService
- Follows SLDS design patterns
- Includes proper meta XML configuration for flexibility in page placement

### CODE REVIEW

**Comment by mlockett** [comment]
Hi Ryan, 

I like adding AuraEnabled to the logger methods. We could also include the _Error_ method and include it in the lwc as well. I've recently thought that this was missing functionality.

Side note: you no longer need to use @track for properties except objects and arrays.

I'm a little skeptical about the unified page. Since the Log Reader component gets updated in realtime, while the standard list view and the App Log Storage component won't be updated until the page is refreshed, the Log Reader will show different data than the standard list. It might be confusing to users and might not add value. I don't want to get bug reports that I have to respond to. :-)

We could add functionality to keep them in sync, but I don't know how much value it adds.

If you're interested in making those changes, I gladly merge them.

**Comment by mlockett** [comment]
Another note: to use Toast, you can include it like this:

import Toast from "lightning/toast";

Then use it like this...

// inside code...
Toast.show({
   mode: 'dismissible', // closes itself after a few seconds
   label: 'Success',
   message: 'Log entry created successfully',
   variant: 'success'
}, this);

You don't need anything in the HTML when using this approach.

**Comment by RyanSchierholz** [comment]
> Hi Ryan,
> 
> I like adding AuraEnabled to the logger methods. We could also include the _Error_ method and include it in the lwc as well. I've recently thought that this was missing functionality.
> 
> Side note: you no longer need to use @track for properties except objects and arrays.
> 
> I'm a little skeptical about the unified page. Since the Log Reader component gets updated in realtime, while the standard list view and the App Log Storage component won't be updated until the page is refreshed, the Log Reader will show different data than the standard list. It might be confusing to users and might not add value. I don't want to get bug reports that I have to respond to. :-)
> 
> We could add functionality to keep them in sync, but I don't know how much value it adds.
> 
> If you're interested in making those changes, I gladly merge them.

Thank you for the update about @track and your patience as I get better on git. 

The intent of the unified page was primarily to reduce clicks between each tab to see the data, or in the case of doing a 'demo' to show a 'realtime' writer that's faster than the screen flow, without readjusting settings each time the Reader tab page is reloaded. Perhaps the storage could have a refresh button and the list view could be removed if you think that would cause confusion. Open to discuss more to find something that is helpful.

**Comment by RyanSchierholz** [comment]
> Another note: to use Toast, you can include it like this:
> 
> import Toast from "lightning/toast";
> 
> Then use it like this...
> 
> // inside code... Toast.show({ mode: 'dismissible', // closes itself after a few seconds label: 'Success', message: 'Log entry created successfully', variant: 'success' }, this);
> 
> You don't need anything in the HTML when using this approach.

yes, I also prefer the built-in toast component. Let me update that...

**Comment by RyanSchierholz** [comment]
Added improvements to the toast notifications:
- Replaced custom toast implementation with Lightning's ShowToastEvent
- Improved user experience with native Salesforce toast styling and behavior
- Simplified code by removing custom toast tracking and HTML
- Better error message display using Lightning's standard toast variants

These changes make the component more aligned with Salesforce platform standards and improve the user experience.

**Pull request closed without merging**
